In [2]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import  classification_report, confusion_matrix

In [6]:
d1 = pd.read_csv('iris.csv')

In [7]:
d1

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
d1.head()
d1.shape

(150, 5)

In [9]:
d1.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [10]:
X=d1.drop('Name',axis=1)

In [11]:
X

SepalLength  SepalWidth  PetalLength  PetalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [12]:
y = d1['Name']

In [13]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: object

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
#knn is object

In [16]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [17]:
y_predict=knn.predict(X_test)

In [18]:
print(confusion_matrix(y_test,y_predict))

[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]


In [19]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.82      0.90      0.86        10
 Iris-virginica       0.89      0.80      0.84        10

       accuracy                           0.90        30
      macro avg       0.90      0.90      0.90        30
   weighted avg       0.90      0.90      0.90        30



In [20]:
# accuracy is 97%

In [21]:
# test size is change


In [22]:

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30)


In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [25]:
y_predict=knn.predict(X_test)

In [26]:
print(confusion_matrix(y_test,y_predict))

[[19  0  0]
 [ 0 14  1]
 [ 0  3  8]]


In [27]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.82      0.93      0.87        15
 Iris-virginica       0.89      0.73      0.80        11

       accuracy                           0.91        45
      macro avg       0.90      0.89      0.89        45
   weighted avg       0.91      0.91      0.91        45



In [28]:
# accuracy is 93%

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.35)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [31]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [32]:
y_predict=knn.predict(X_test)

In [33]:
print(confusion_matrix(y_test,y_predict))

[[15  0  0]
 [ 0 20  0]
 [ 0  2 16]]


In [34]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.91      1.00      0.95        20
 Iris-virginica       1.00      0.89      0.94        18

       accuracy                           0.96        53
      macro avg       0.97      0.96      0.96        53
   weighted avg       0.97      0.96      0.96        53



In [35]:
#accuracy is 96%


In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.40)

In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [38]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [39]:
y_predict=knn.predict(X_test)

In [40]:
print(confusion_matrix(y_test,y_predict))

[[18  0  0]
 [ 0 23  1]
 [ 0  2 16]]


In [41]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        18
Iris-versicolor       0.92      0.96      0.94        24
 Iris-virginica       0.94      0.89      0.91        18

       accuracy                           0.95        60
      macro avg       0.95      0.95      0.95        60
   weighted avg       0.95      0.95      0.95        60



In [42]:
# accuracy is 93%

### neighbor 2

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.40)

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)

In [45]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [46]:
y_predict=knn.predict(X_test)

In [47]:
print(confusion_matrix(y_test,y_predict))

[[26  0  0]
 [ 0 20  1]
 [ 0  4  9]]


In [48]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        26
Iris-versicolor       0.83      0.95      0.89        21
 Iris-virginica       0.90      0.69      0.78        13

       accuracy                           0.92        60
      macro avg       0.91      0.88      0.89        60
   weighted avg       0.92      0.92      0.91        60



In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30)

In [51]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)

In [52]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [53]:
y_predict=knn.predict(X_test)

In [54]:
print(confusion_matrix(y_test,y_predict))

[[20  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [55]:
print(classification_report(y_test,y_predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        20
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.97        45
   weighted avg       0.98      0.98      0.98        45

