In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
bankdata = pd.read_csv("bill_authentication.csv")

In [4]:
bankdata.shape

(1372, 5)

In [5]:
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [6]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']

### linear|

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.20)

In [83]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [84]:
y_pred = svclassifier.predict(X_test)

In [85]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[149   0]
 [  1 125]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       149
           1       1.00      0.99      1.00       126

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.30)

In [87]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [88]:
y_pred = svclassifier.predict(X_test)

In [89]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[218   3]
 [  1 190]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       221
           1       0.98      0.99      0.99       191

    accuracy                           0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412



In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.35)

In [91]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [92]:
y_pred = svclassifier.predict(X_test)

In [93]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[260   4]
 [  1 216]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       264
           1       0.98      1.00      0.99       217

    accuracy                           0.99       481
   macro avg       0.99      0.99      0.99       481
weighted avg       0.99      0.99      0.99       481



In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.40)

In [95]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [96]:
y_pred = svclassifier.predict(X_test)

In [97]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[303   5]
 [  3 238]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       308
           1       0.98      0.99      0.98       241

    accuracy                           0.99       549
   macro avg       0.98      0.99      0.99       549
weighted avg       0.99      0.99      0.99       549



### sigmoid

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.20)

In [29]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [30]:
y_pred = svclassifier.predict(X_test)

In [31]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[94 67]
 [37 77]]
              precision    recall  f1-score   support

           0       0.72      0.58      0.64       161
           1       0.53      0.68      0.60       114

    accuracy                           0.62       275
   macro avg       0.63      0.63      0.62       275
weighted avg       0.64      0.62      0.62       275



In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.30)

In [33]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [34]:
y_pred = svclassifier.predict(X_test)


In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[152  73]
 [ 65 122]]
              precision    recall  f1-score   support

           0       0.70      0.68      0.69       225
           1       0.63      0.65      0.64       187

    accuracy                           0.67       412
   macro avg       0.66      0.66      0.66       412
weighted avg       0.67      0.67      0.67       412



In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.35)

In [38]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [39]:
y_pred = svclassifier.predict(X_test)


In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[195  62]
 [ 81 143]]
              precision    recall  f1-score   support

           0       0.71      0.76      0.73       257
           1       0.70      0.64      0.67       224

    accuracy                           0.70       481
   macro avg       0.70      0.70      0.70       481
weighted avg       0.70      0.70      0.70       481



In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.40)

In [42]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [43]:
y_pred = svclassifier.predict(X_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[208  83]
 [ 96 162]]
              precision    recall  f1-score   support

           0       0.68      0.71      0.70       291
           1       0.66      0.63      0.64       258

    accuracy                           0.67       549
   macro avg       0.67      0.67      0.67       549
weighted avg       0.67      0.67      0.67       549



### Gaussian

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.20)

In [61]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [62]:
y_pred = svclassifier.predict(X_test)

In [63]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[154   3]
 [  0 118]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       157
           1       0.98      1.00      0.99       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.30)

In [64]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [65]:
y_pred = svclassifier.predict(X_test)

In [66]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[154   3]
 [  0 118]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       157
           1       0.98      1.00      0.99       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.35)

In [72]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [73]:
y_pred = svclassifier.predict(X_test)

In [74]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[272   0]
 [  0 209]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       272
           1       1.00      1.00      1.00       209

    accuracy                           1.00       481
   macro avg       1.00      1.00      1.00       481
weighted avg       1.00      1.00      1.00       481



In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test =train_test_split(X,y, test_size =0.40)

In [79]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [98]:
y_pred = svclassifier.predict(X_test)

In [101]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[303   5]
 [  3 238]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       308
           1       0.98      0.99      0.98       241

    accuracy                           0.99       549
   macro avg       0.98      0.99      0.99       549
weighted avg       0.99      0.99      0.99       549

